### ISSUE TITLE
type adaption in sqla/psycopg2 to match SQL types

### ISSUE THREAD

**Issue by nesnoj** [openego/ego.io#1]
When adding a dataset to a table via sqla, e.g.

```
dataset = mapped_sqla_object(attr1=var_int, attr2=var_str)
session.add(dataset)
```

throws

```
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) can't adapt type 'numpy.int64'
```

Variable `var_int` is of type 'numpy.int64' so I seems psycopg2 doesn't know how to map the numpy to SQL-conform type (sqla column type is defined as 'sqla.Integer').

I found a [solution](http://initd.org/psycopg/docs/advanced.html#adapting-new-python-types-to-sql-syntax) using a psycopg2 extension using `register_adapter()`.
To avoid having it in every single tool, @MGlauer proposes to make it a part of the planned ego.io-packages `__init__.py`, i.e. if you use `import ego.io` this adapter will be automatically registered.

([issue in dingo](https://github.com/openego/dingo/issues/26))

**Comment by gplssm** [comment]
I already did it some time ago, see 8e7c64e0e9868b9bbc3156c70f6c368cad427f1f.
