### ISSUE TITLE
Cannot import name ARRAY (sqlalchemy)

### ISSUE THREAD

**Issue by simnh** [openego/ego.io#11]
Hi, running hv_grid.py from ego.powerflow exampels I get the following error: 
 
```
  from sqlalchemy.dialects.postgresql.base import ARRAY
ImportError: cannot import name 'ARRAY'
```

I can import ARRAY though from `sqlalchemy.dialects.postgresql` 

Using sqlalchemy 1.1.4 

Anyone similar problems?

**Comment by simnh** [comment]
Solving this (just by another import) I know have the error 'ResBus' as well #9 . I merge the `dev` branch into features/clustering. (inside the ego.powerflow repository) Was that not a good idea, or should I take the master?

**Comment by ulfmueller** [comment]
@simnh : I posted the 'quick and dirty' workaround in #9 ... but it works for now. Does it work for you?

**Comment by simnh** [comment]
works with the solution from issue #9

**Comment by gplssm** [comment]
I'm interested in solving this issue without working around it.

I can't find any import like
```
  from sqlalchemy.dialects.postgresql.base import ARRAY
```

Neither in ego.io nor ego.powerflow. We changed the all to SQLAlchemy >=1.0.15 compatible statement. Which version of ego.* are you using?

**Comment by simnh** [comment]
Yeah I was on a old commit in ego.io, where this ARRRAY was inside the code somewhere. Now with being on v.0.0.2 on both repos it works! see (wrote it here as well #9)
