### ISSUE TITLE
release ego.io v0.2

### ISSUE THREAD

**Issue by nesnoj** [openego/ego.io#14]
Prior to the data_proc v0.2 release we need a new release of ego.io.
ToDos:

- [x] Delete orphaned branches #13 (@nesnoj)
- [x] Create new table defs #8 (@MGlauer)
- [x] Version: I propose to use v0.2 for the next release according to data_proc v0.2 - any objections?
- [x] Adjust setup.py (@nesnoj)
- [x] Release via PyPi (@nesnoj)

To my mind, we could postpone the documentation via RTD to a later release.

Any further issues to be considered?

**Comment by ulfmueller** [comment]
Thanks for the good check list! I agree mostly. Only I do not understand the necessity of replacing the oemof.db access. Isn't that a fine working tool?
I would add one 'issue' of merging the refactored branch to the master (but that is probably part of the last check box).

**Comment by nesnoj** [comment]
I agree and opened a new issue for the merge #15.
oemof.db is great but to ensure a proper functionality of db access in the future and to reduce our dependencies I'd prefer to use our own interface. If there will be substantial improvements to oemof.db one day we still can adopt them in ego.io.
Open for different opinions :)

**Comment by ulfmueller** [comment]
I guess I do not see the problem of the dependency. I like the idea to use stuff which has been developed already - especially when we talk about 'our' framework oemof. Isnt that also the idea of a framework - to use as much as you can from it without rebuilding it? As well we have dependencies to e.g. PyPSA. It is already the case that we work on an old version of PyPSA which is fine and anyhow could be adjusted later. But maybe it is a different kind of dependency here which I do not understand...
How much effort is it to integrate the oemof.db access functionality?

**Comment by nesnoj** [comment]
Ok that's right, I get your point. And furthermore we will use oemof anyway so oemof.db will be a requirement..

In either case we might aspire to bundle db access stuff in ego.io tools - currently db access is done using
1. oemof.db import statements (e.g. [here](https://github.com/openego/data_processing/blob/refactor/oedb-restructuring_v0.2/dataprocessing/python_scripts/peak_load_per_load_area.py#L19))
2. [data_proc io](https://github.com/openego/data_processing/blob/refactor/oedb-restructuring_v0.2/dataprocessing/tools/io.py) (e.g. [here](https://github.com/openego/data_processing/blob/refactor/oedb-restructuring_v0.2/dataprocessing/eGo_data_processing.py#L17))
3. [ego.powerflow tools](https://github.com/openego/ego.powerflow/blob/dev/egopowerflow/tools/tools.py) (e.g. [here](https://github.com/openego/ego.powerflow/blob/dev/egopowerflow/examples/hv_grid.py#L14))

We could move the `oedb_session()` function to ego.io and adjust all scripts in all repos to use it..?

**Comment by ulfmueller** [comment]
That sounds like a very nice improvement!More modularized and less redundant!Who and when?
For me it would be ok to postpone it to a later version. But if it is a easy thing you can and want to do quickly...

**Comment by nesnoj** [comment]
In https://github.com/openego/data_processing/issues/13 it is on schedule for v0.3. I created a new issue #16 and ego.io v0.3 milestone so we'll come back to this later.

**Comment by eosram** [comment]
Maybe we should include the small sqlacodegen bash script for mapping oedb schemata by @MGlauer (#8) in the upcoming release. I just talked to @nesnoj about it and we agreed, that it could be part of it. Maybe egoio/tools would be a reasonable location. Do we need to change the script in any way before doing that, e.g. implementing a more secure way of providing credentials?

**Comment by nesnoj** [comment]
Good point. egoio/tools seems like a good location..

These are some issues related to the integration:
1. Issues of sqlacodegen itself - I guess we can only use a workaround or edit the result manually:
1.1 Data types and attr. "meta_data": https://github.com/openego/ego.io/issues/8#issuecomment-279395139
1.2 Integration of GeoAlchemy2: https://github.com/openego/ego.io/issues/8#issuecomment-280599801
2. Alternative to raw credentials - use keyring (never used on bash...) or ask for credentials during execution.
3. Add description

**Comment by eosram** [comment]
As previously pointed out there is an odd bug creating the class for table ego_grid_pf_hv_bus. This class is named EgoGridPfHvBu.

**Comment by eosram** [comment]
Fixed it in 216b684af736848cbcdb463da91b8e66febc4ea6 . Still have no idea why it's happening.

**Comment by nesnoj** [comment]
It is now documented in https://github.com/openego/ego.io/issues/8#issuecomment-302099463 .

**Comment by gplssm** [comment]
@nesnoj, I thought you were done with the ego.io release... I was looking around because I wanted to update dependencies of Dingo accordingly (for installation test purpose) but I haven't a new release. Could you say when I can expect the next release to be published?

**Comment by nesnoj** [comment]
I'll do it within the next days..

**Comment by nesnoj** [comment]
The release of v0.2.0 is done!

1. merged `dev` to `master`
2. created tag `v0.2.0`
3. released via PyPI
4. deleted orphaned branches

Please use `dev` for further work.

For the next release I wrote down some issues which came up and we have to consider/talk about in #22.
