### ISSUE TITLE
Numpy version 1.11.3 (Windows related)

### ISSUE THREAD

**Issue by mariusves** [openego/ego.io#17]
Installing ego.io on windows using pip sometimes doesn't work due to numpy failing to install correctly (failed building wheel for numpy).
The usual workaround for this is to install numpy manually from this site, which provides most of the python packages prepared for Windows: 
http://www.lfd.uci.edu/~gohlke/pythonlibs/#numpy

The problem is that the lowest available version is 1.11.3, while ego.io demands 1.11.2.
AFAIK this new version of numpy is just a minor bugfix and should not cause any further problems with ego.io.

Is it possible to adjust the setup.py to allow this?

**Comment by nesnoj** [comment]
Done in 91988d6edf1adc2ddc60b60b978ffcda54d856d8 (untested).
