### ISSUE TITLE
Tidy up branches

### ISSUE THREAD

**Issue by eosram** [openego/ego.io#18]
All of the commits of branch refactor/adaptations-of-table-names are contained in the branch refactor/updated_schema_structure except one. In this commit a __tablename__ argument is changed from 'ego_demand_loads' to 'ego_demand_loadarea' in line 137 of calc_ego_loads.py. Could we maybe adapt refactor/updated_schema_structure accordingly and remove refactor/adaptations-of-table-names afterwards? Are there any objections? 

At ZNES we don't use refactor/adaptations-of-table-names anymore.

**Comment by eosram** [comment]
In addition maybe we can rename the refactor/updated_schema_structure to dev?

**Comment by eosram** [comment]
I would do both if you all agree : ).

**Comment by eosram** [comment]
Looking into #13, which the current issue kind of duplicates. Can the orphaned reload and features/map-visualization branches be removed?

**Comment by gplssm** [comment]
features/map-visualization contains some experimental stuff, I don't want to loose. Two options

1. We keep this branch there
2. If you want to have the repo and just keep branches that are relevant for current development, I would a local copy.

It's up to you, @s3pp just tell me!

**Comment by nesnoj** [comment]
Feel free to merge `refactor/updated_schema_structure` to `dev` (or do a pull request). 
You can omit the [commit](https://github.com/openego/ego.io/commit/70d08715421c33f762abb0b72935d99817583bf7)  you mentioned above since it refers to old unused tables.
You want me do do it (it was assigned to me in #13) - otherwise: thanks for doing my tidy-up job ;)

For the dp release (and hence the table structure is final) I will do the ego.io release..see #14. As soon as you finish the tidy-up, please tick the corresponding box in #14.

**Comment by eosram** [comment]
Thanks for your feedback! Let's keep it then @gplssm ! I just wasn't sure if the branch is still used. As proposed I deleted the refactor/adaptations-of-table-names branch : ). I created a development branch based on master and a pull request from refactor/updated_schema_structure to dev.

**Comment by gplssm** [comment]
Thanks!

Don't put too much effort on the merge. For the RLI its fine to only keep the branch refactor/updated_schema_structure. Thus, we would be happy when master and dev are overwritten by this branch.

**Comment by gplssm** [comment]
I tested dev branch with Dingo - works! Thanks a lot @s3pp ! I delete "refactor/updated_schema_structure".

What about [this branch](https://github.com/openego/ego.io/tree/28f7dd428ca46e44649f6043cc685c90da51269e)  @nesnoj created? I think we can delete it as well.

**Comment by gplssm** [comment]
Furthermore, I set "dev" as standard branch for ego.io

**Comment by eosram** [comment]
Thank you @gplssm!

**Comment by nesnoj** [comment]
I think this one is done. dp 0.2 release is prepared in #8.
