### ISSUE TITLE
fix bugs in sqlacodegen's defs

### ISSUE THREAD

**Issue by nesnoj** [openego/ego.io#21]
See no. 3.-6. in [wiki](https://github.com/openego/ego.io/wiki/How-to-update-database-definitions).
@MGlauer Have you got any hints on this?

**Comment by MGlauer** [comment]
5. Ok, i took the time to read through the sqlacodegen code. By default, tailing s letters are considered as plurals and inflected (i.e. the s is cropped). This can be prevented by the parameter --noinflect (but this might affect other tables, too)

**Comment by MGlauer** [comment]
3. These types should not exist at all in the python code. they are translated (e.g. double precision -> Float). But this seems to be broken for Arrays. I opened a [bug report](https://github.com/agronholm/sqlacodegen/issues/46)

**Comment by MGlauer** [comment]
4. I guess there is no way to fix this other than renaming the column

**Comment by nesnoj** [comment]
Wow, tanks for your efforts! :+1: 

Concerning
3. We wait for an answer, they might fix it (or use your fork :)
4. https://github.com/openego/data_processing/issues/102
5. sqlacodegen seems to use `engine.singular_noun()` from inflect (e.g. [here](https://github.com/agronholm/sqlacodegen/blob/4956c681d88da5ebc81ac3d276a458dce3876766/sqlacodegen/codegen.py#L191)) only to remove plural from **last word** of table name. As the *Bus-tables are the only ones who show this problem, I actually guess that no other tables will be affected. So for the next release I'd give it a try with the `--noinflect` option...

**Comment by Ludee** [comment]
metadata/meta_data is fixed!

**Comment by nesnoj** [comment]
Thx! I adjusted the wiki.

**Comment by gplssm** [comment]
As this is quite old and maybe outdated, I close. Please open a new issue if problems arise with upcoming releases.
