### ISSUE TITLE
release v0.3.0

### ISSUE THREAD

**Issue by nesnoj** [openego/ego.io#22]
Now as the v0.2.0 release is done, this is the main issue for the next major release (v0.3.0).
I've set version to v0.3.0 in setup.py of `dev`.

Things we have to consider/talk about in [`setup.py`](https://github.com/openego/ego.io/blob/a39e879710e48fe8ae2b79983bd6bf1df8b16dc5/setup.py#L14):

- [x] I did not work on adjusting the versions of required packages. Adjust requirements and might harmonize required versions in all repos?
- [x] The [`sqlacodegen_oedb.sh`](https://github.com/openego/ego.io/blob/dev/egoio/tools/sqlacodegen_oedb.sh) is not included in v0.2.0 PiPI release. To include *.sh files in v0.3.0, we need a section `package_data` ([example in dingo](https://github.com/openego/dingo/blob/b319e8ab06231e70da307593594a116dcbced701/setup.py#L46)).
- [x] Set `author_email` - We do not have a main eGo address, do we?
- [x] (Optional?) Fix bugs in sqlacodegen's defs #21

**Comment by nesnoj** [comment]
@IlkaCu Please notify me as soon as v0.3.0 is done and I will create a new release here..

One more thing @ulfmueller @IlkaCu @gplssm @wolfbunke @mariusves @birgits:
> I did not work on adjusting the versions of required packages. Adjust requirements and might harmonize required versions in all repos?

Obviously, we will get into trouble here 'cause the version requirements in [eTraGo](https://github.com/openego/eTraGo/blob/8db3dc0c70c00c011c42ac94674e41754136e704/setup.py#L17-L24) and [eDisGo](https://github.com/openego/eDisGo/blob/573c9fda1286b619d818809045c5bb63e678215a/setup.py#L33-L40) (+[ding0](https://github.com/openego/ding0/blob/f46db597dfd4a9b193345880d4cda1d3764b7d23/setup.py#L32-L46)) do not overlap (e.g. pandas). We must harmonize versions here.
I propose that the eTraGo team and the eDisGo team check if they tools run with the latest package versions (if I'm not mislead, pandas v0.21 causes some trouble?!)

**Comment by nesnoj** [comment]
Comments on the harmonization issue above, anyone?

@IlkaCu: Are you done with v0.3.0? If yes, I will prepare a release today..

**Comment by IlkaCu** [comment]
@ulfmueller revealed some major bugs in the version 0.3.0, therefore I did not finish the release yet. I'll try to find and fix the bugs as soon as possible.

**Comment by gplssm** [comment]
I would like to head for a new release - v0.3.0.
Therefore, I'll resolve task from above and then do the whole process of creating a new version.

@IlkaCu as far as I understood we have a successful DP run including versioned data. Can you confirm this?

@ulfmueller what about the mail address for the package metadata?

Who would like to review the PR?

**Comment by ulfmueller** [comment]
Thx for dealing with this @gplssm !

> what about the mail address for the package metadata?

We do not have an open_eGo email address. I am not sure who to put there in this case. I would say one of the main developer or a person who feels the most responsible. You can put yours or mine if you want.

> Who would like to review the PR?

I can review the PR. But maybe also @IlkaCu since she probably knows the dp v0.3.0 the best.

**Comment by IlkaCu** [comment]
> @IlkaCu as far as I understood we have a successful DP run including versioned data. Can you confirm this?

That's right. The DP run was successful, corresponding data is versioned and we have a new release v0.3.0 in the DP repository. 

> I can review the PR. But maybe also @IlkaCu since she probably knows the dp v0.3.0 the best.

Feel free to add me as an additional reviewer here.

**Comment by ulfmueller** [comment]
@gplssm When do you plan to release the ego.io 0.3.0?

**Comment by gplssm** [comment]
It seems like I have to postpone after christmas :disappointed:

**Comment by gplssm** [comment]
Further discussion in #45

**Comment by gplssm** [comment]
Dependencies' versions are update and harmonized with linking packages. Corrections of the ORM classes are done for this specific release. Those were tested using https://github.com/openego/etrago, https://github.com/openego/ding0 and https://github.com/openego/eDisGo
