### ISSUE TITLE
pimp wiki

### ISSUE THREAD

**Issue by nesnoj** [openego/ego.io#23]
1. Please amend [How-to-release](https://github.com/openego/ego.io/wiki/How-to-release)
2. How long are we gonna wait from pull request to merge? (see [wikipage](https://github.com/openego/ego.io/wiki/How-to-update-database-definitions) no. 8)

**Comment by gplssm** [comment]
This wiki was updated during last release, but there are still things to do. Please go ahead with this!

**Comment by nesnoj** [comment]
Outdated
