### ISSUE TITLE
update data types from NUMERIC to DOUBLE_PRECISION

### ISSUE THREAD

**Issue by Ludee** [openego/ego.io#27]
We will change data types from `NUMERIC` and `DECIMAL` to `DOUBLE_PRECISION`
https://github.com/openego/data_processing/issues/72
ego.io has to be updated as well.

I'm not sure how to handle `FLOAT`. Any idea? @gplssm @nesnoj

**Comment by nesnoj** [comment]
`FLOAT` is a postgreSQL-specific type. The [docs](https://www.postgresql.org/docs/9.3/static/datatype-numeric.html) say

> PostgreSQL also supports the SQL-standard notations float and float(p) for specifying inexact numeric types. Here, p specifies the minimum acceptable precision in binary digits. PostgreSQL accepts float(1) to float(24) as selecting the real type, while float(25) to float(53) select double precision. Values of p outside the allowed range draw an error. float with no precision specified is taken to mean double precision.

So you can simply replace `FLOAT` by `DOUBLE PRECISION` in dp as there're [no occurences](https://github.com/openego/data_processing/search?l=SQL&q=float&type=&utf8=%E2%9C%93) with specified precision.

**Comment by nesnoj** [comment]
Approved in #30: No NUMERIC left (except in model_draft).
