### ISSUE TITLE
class naming and usability

### ISSUE THREAD

**Issue by nesnoj** [openego/ego.io#3]
Thank you @MGlauer for the sqla class definitions!

The classes are strictly named after Tables and CamelCase. When using within tools, I'd appreciate to see immediately that I'm using a sqla object and not a tool's class. What about adding a prefix like `sqla_` or similar to all classes?

**Comment by gplssm** [comment]
Is resolved by 2d652bafe124b51875c63d14b458bd70a2500a3b

**Comment by gplssm** [comment]
@nesnoj maybe I was too fast by clicking on 'close'... I assumed you just wanted to have prefixes in Dingo. Was your intention to have the prefixes saying that these are SQLA-objects directly in ego.io?

**Comment by nesnoj** [comment]
We could handle this like you already did [in Dingo](https://github.com/openego/dingo/blob/2d652bafe124b51875c63d14b458bd70a2500a3b/dingo/core/__init__.py#L19-L22) or go for a more general solution in ego.io as proposed above.
That depends on the preference of all involved developers...more comments, anyone?

**Comment by nesnoj** [comment]
Ok, nobody seems to care, so do I :)
