### ISSUE TITLE
oemof.db in setup requirements missing?

### ISSUE THREAD

**Issue by mariusves** [openego/ego.io#38]
While checking out the ego.io db tools [here](https://github.com/openego/ego.io/blob/master/egoio/tools/db.py) I noticed that in the requirements section in the setup.py oemof.db is not listed.

I'm quite sure that oemof isn't a requirement of any other of the three listed packages and therefore it  probably isn't available on a fresh install (can't test right now) and might cause a bug.

Is this assumption correct? Also, on which version of oemof.db is the above linked function based on?

**Comment by nesnoj** [comment]
Yes, you're right, thank you! It should be included in the `setup.py`.
The current version runs successfully with version 0.0.5.
Could you please add it? (in `dev` branch)

**Comment by mariusves** [comment]
Thanks for the quick feedback. Requirements have been updated!
