### ISSUE TITLE
delete orphaned branches

### ISSUE THREAD

**Issue by nesnoj** [openego/ego.io#40]
I'd like to delete outdated/orphaned/closed branches:
```
remotes/origin/features/add-pf-result-tables
remotes/origin/features/map-visualization
remotes/origin/features/own-config-file
remotes/origin/features/release_v0.2.10
remotes/origin/features/release_v0.2.10_with_db_interface
remotes/origin/fix/schema_rename
remotes/origin/refactor/adapt-to-v0.3.0-db-structure
```
Anyone using one of these branches?

If not, I will delete them on Wednesday night..

**Comment by mariusves** [comment]
features/add-pf-result-tables is deleted now (wasn't needed anymore after successful PR)

**Comment by wolfbunke** [comment]
No, I am not working on this branches.

**Comment by gplssm** [comment]
I rescued WIP from remotes/origin/features/map-visualization and save it elsewhere.

Thanks for cleaning up :+1:

**Comment by nesnoj** [comment]
done
