### ISSUE TITLE
Rename column metadata to meta_data in EgoScenarioInput

### ISSUE THREAD

**Issue by gplssm** [openego/ego.io#44]
While creating a new version of ego.io I noticed a bug that was already resolved appears again (manually fixed in 0e3a110df55b3c9c353bac896b4d5355e6365ccc). I order to avoid it the next time, we should fix it properly at the right place. Do I get it right that we "simply" have to rename the column "metadata" of table "model_draft.ego_scenario_input" to "meta_data" and adjust all references? Please note, when I talk about renaming I mean actual renaming of the database column.

I would appreciate your advice @Ludee @nesnoj

**Comment by nesnoj** [comment]
Yes, I guess so. @Ludee did the renaming last time -> related issue in DP: https://github.com/openego/data_processing/issues/102

**Comment by Ludee** [comment]
I wasn't aware of this scenario_input table yet.
It looks like a good idea.
Can you tell me where and how it is created?
Renaming the column in the database is quite simple:
`ALTER TABLE model_draft.ego_scenario_input
RENAME COLUMN metadata TO meta_data;`
 
UPDATE: My future me liked the work I did a couple of month ago. But wasn't that good that I remembered right away.

**Comment by gplssm** [comment]
> Can you tell me where and how it is created?

Nope, no idea - sorry!

**Comment by Ludee** [comment]
Found the script. I created it and forgot it ;)

Database table renamed.
Script adjusted.
Pushed to dp/dev.
https://github.com/openego/data_processing/commit/4c08c22786847f5db54dee2fc8a5c53ab6c18e4e

**Comment by nesnoj** [comment]
I recreated the defs recently and now we got the same problem in `model_draft.scenario_log`.
The metadata blames you, @Ludee ;)

**Comment by Ludee** [comment]
Are you sure about the table _model_draft.scenario_log_?
There is no column _metadata_

Perhaps it is still _model_draft.ego_scenario_input_ with columns _metadata_reference_date_?

**Comment by nesnoj** [comment]
Yes it's `model_draft.scenario_log`, I just checked with pgAdmin..

**Comment by Ludee** [comment]
Ok, I confused scenario_log for different projects with ego_scenario_log.
Column renamed

**Comment by nesnoj** [comment]
cheers!
