### ISSUE TITLE
non-ASCII chars in names

### ISSUE THREAD

**Issue by nesnoj** [openego/ego.io#50]
There're some tables and views which have "ß" in their names ("Gießen"), see example below. Usage of non-ASCII charset might work with postgreSQL but cause problems with interfacing tools such as sqlacodegen.
During recreation of table defs, the lines containing special characters (at least this one) seem to be embraced by sqlacodegen (`"ev_charging_streets_gießen_id_seq"`) which subsequently causes errors in python.

Probably, special chars can be easily catched when the webinterface (or the upcoming dialect) is used but it's a mess with the direct SQL access. Those tables and views should be renamed, otherwise this needs to be fixed manually at every run..

Who is responsible here? (there're no meta data)

```
class EvChargingStreetsGießen(Base):
    __tablename__ = 'ev_charging_streets_gie\xdfen'
    __table_args__ = {'schema': 'model_draft'}

    id = Column(Integer, primary_key=True, server_default=text("nextval('model_draft."ev_charging_streets_gießen_id_seq"'::regclass)"))
    osm_id = Column(Integer)
    geom = Column(Geometry('LINESTRING', 3035), index=True)
    length = Column(Numeric)
    highway = Column(HSTORE(Text()))
```

**Comment by nesnoj** [comment]
Still no answers here.
Who created those tables? (I'll try to find out whether it's someone at RLI..)

**Comment by ulfmueller** [comment]
Dont think it was anyone in ZNES. But I will ask here as well...

**Comment by nesnoj** [comment]
Found the offender.
Fixed it.
Rule added to DatabaseRules: https://wiki.openmod-initiative.org/wiki/DatabaseRules#Database_Table

@ulfmueller Please note here if there're more tables affected..
