### ISSUE TITLE
Quick-little-new ego.io release

### ISSUE THREAD

**Issue by ulfmueller** [openego/ego.io#54]
I would like to realize a small ego.io release which includes #53 in order to be able to release a new version of eTraGo. The additional tables which were added to the io definition should not interfere with any other applications.

Any objections?

I would call it 0.3.1

**Comment by gplssm** [comment]
I'm fine with it! @boltbeard does a release v0.3.1 help to resolve you stuff? Like new ORM class definitions...

**Comment by ulfmueller** [comment]
@boltbeard I would like to release eTraGo within this week. Therefore I would be happy to get a quick feedback from you if possible.
Well in my mind it would be no problem to release a 0.3.2 soon afterwards if needed. Anyhow there will be a 0.4.0 I guess due to the new dp release very soon...

**Comment by ulfmueller** [comment]
@nglsrrl commited 2 quite big changes to the dev branch without any pull request ( 3b90f63b99a0b2e65894a4a6f8e644bdbd88fee2 and https://github.com/openego/ego.io/commit/267092e7c3c83ca6062cab7f41775382ffee634f ). Pulling from dev in order to prepare the merging of #53 I noticed that and I am not sure weather all these changes are wanted and do not interfere with anything. Some changes such [as](https://github.com/openego/ego.io/commit/3b90f63b99a0b2e65894a4a6f8e644bdbd88fee2#diff-ae21b2456db73b963e0f59330d8dfcaeR1415) made me suspicious. Also my email was posted as an author email without asking.  
Did anyone check these changes? Are you aware of these changes? Are you ok with them? @gplssm @wolfbunke @nesnoj ...

**Comment by ulfmueller** [comment]
having a look at the recent table definitions in the oedb it seems that some changes are not up-to-date. e.g. looking at ego_dp_supply_res_powerplant the w_id is missing...

**Comment by ulfmueller** [comment]
well, since the commits have been on dev for over 3 weeks I would assume that the changes are ok or at least do not bother.  If no one stops me I will create a release 0.3.1 today early afternoon.

**Comment by gplssm** [comment]
I instructed @nglsrrl to include these changes. The idea why we directly included it in dev was that it will be overwritten anyways once the sqlcodegen script is executed. I thought the next release of ego.io would be according to the new DP version...

The changes that are suspicious to you are as well suspicious to me. The actual intention of @nglsrrl was to add only new table definitions for ding0 data. 
The fact you are mentioned as author was discussed with you earlier (2-3 month) and it was me that added your mail address.

To conclude, new class definitions for ding0 data should be kept. The other changes in 3b90f63b99a0b2e65894a4a6f8e644bdbd88fee2 are unknown to me... I would assume something was merged there because some of these change date back longer.
Go for the release on your own responsibility. But actually nothing too bad can happen, because everyone could stay with v0.3.0.

**Comment by ulfmueller** [comment]
Thx @gplssm for your clarifications. Sorry, that I forgot the authorship thing (I remember now :wink: ). 

Do you think the merge 3b90f63b99a0b2e65894a4a6f8e644bdbd88fee2 went wrong in the sense that new stuff got overwritten by old stuff? I will dig a bit deeper in order get a rather clean release.

Yeah you are right if the release is not that clean, there is 0.3.0 and there is 0.4.0 coming soon overwriting everything. Maybe I should not bother too much...

**Comment by nesnoj** [comment]
Please be aware of #50 (still unsolved) which would prevent you from using your ego.io release.
For your release it may be the fastest solution to simply delete those defs manually after sqlacodegen in order to create a working version.

**Comment by ulfmueller** [comment]
You mean, run sqlcodegen, do the manual debugging such as change bu to bus (as described in 
the [wiki](https://github.com/openego/ego.io/wiki/How-to-update-database-definitions) ) ?
I was planning to release without using sqlcodegen. But you got a point there, maybe it would be better, cleaner and easier to do so. 
Just to be sure I did not misunderstood you, what do you mean by 'simply delete those defs manually'? The bu to bus stuff, the #50 or left-overs of 3b90f63b99a0b2e65894a4a6f8e644bdbd88fee2 or altogether?

**Comment by nesnoj** [comment]
Sorry for this misleading comment.
Yes, I'd strongly recommend to run sqlacodegen.
Subsequently, 1) follow the wiki (also for the manual adjustments), 2) delete the defs which contain non-ASCII chars (gießen..unsure if there're more) #50
Got no idea whether 3b90f63 involves more manual changes or a re-generation creates those defs and everything will be fine..

If you like, create a PR and I can re-check..

**Comment by gplssm** [comment]
To be honest, I don't have any further idea on 3b90f63b99a0b2e65894a4a6f8e644bdbd88fee2

**Comment by ulfmueller** [comment]
Thx @nesnoj !

I (and the people involved) have not finally decided it but I am thinking to save the time for the release and just postpone our eTraGo release and wait for the dp 0.4.0 (which hopefully will be ready in the next 7 days or so) Then I/we have to do this just once at not twice in a short period of time. 
I didnt think to spend so much time with this...
So if I do a 0.3.1 it wont be today and probably there will be not one at all. 
Sorry for bothering you but anyhow I think it was a good preparation (at least for me) for the upcoming 0.4.0 release (which I can do then and like you suggested I will assign you @nesnoj as a reviewer).

I will leave this issue open until we decide...
