### ISSUE TITLE
Change or add the oeddialect to ego.io

### ISSUE THREAD

**Issue by wolfbunke** [openego/ego.io#58]
In order to integrate the new oedialect the function of  ego.io should be changed.

See:
* https://github.com/openego/ego.io/blob/dev/egoio/tools/db.py#L229
* https://github.com/openego/oedialect

**Comment by ulfmueller** [comment]
@gnn is in charge of that task. We talked about this on the last project meeting. @gnn What is the status here?

**Comment by wolfbunke** [comment]
The pull request is done by @MGlauer in  #59. I think we can close this issue @ulfmueller @gplssm please take a look on the changes.

**Comment by gplssm** [comment]
Done! At latest with the [oedialect v0.0.1](https://pypi.org/project/oedialect/0.0.1.dev0/) :confetti_ball: :clap:
