### ISSUE TITLE
Release 0.4.1

### ISSUE THREAD

**Issue by ulfmueller** [openego/ego.io#62]
In this 66b006b47d9fe782760c17878155e218c2a1784d I manually corrected table definitions in order to have some functionalities working in eTraGo.

This wednesday an eTraGo release is planned. Therefore it would be good to create a new release for eDisGo since eTraGo would not completely run with the current ego.io release. 

I would suppose that I create a new release. I guess the best way is to run codegen and do it like described in the wiki. In contrast I am tempted to base a release on the actual dev. Any opinions / suggestions on this ? 
@gplssm @wolfbunke  If I prepare a new release in a release branch today, would it be possible for you to review a corresponding PR until wednesday?

**Comment by ulfmueller** [comment]
add-on: 
dp 0.4.1 was released last week.
dp 0.4.2 is running at the moment. 

So it would be not a good idea to perform codegen on a running process.
Therefore I would suggest to create a ego.io 0.4.1 just being based on the current dev. The only changes since the last release are the corrections I made for a particular eTraGo fuctionality which has no implications for eDisGo or other tools. 

For dp 0.4.2 we can do the codegen again. 

I think this work-flow is reasonable. Do you agree?

**Comment by gplssm** [comment]
:+1: go for it!

**Comment by gplssm** [comment]
Wait.... I figured out that now the `w_id` is [now included in versioned supply mviews/tables](https://github.com/openego/data_processing/pull/276). I would like to include in v0.4.1 to make ding0/eDisGo run again. I'll try to provide a feature branch ASAP.

**Comment by ulfmueller** [comment]
Good morning @gplssm ! Any news already?

**Comment by gplssm** [comment]
Some corrections/modifications in the OEDB were needed to make it compatible with ego.io and ding0. This was done by https://github.com/openego/data_processing/issues/299.

Please include this PR in the release: https://github.com/openego/ego.io/pull/63 It has minor modifications for tables/mviews in supply schema that are relevant to ding0.

Please also keep in mind the [usual steps of a release](https://github.com/openego/ego.io/wiki/How-to-release) like setting correct version, etc. although your skipping the codegen part.

**Comment by ulfmueller** [comment]
Did  #63 solve your problem entirely so that I can take the current dev as a base for the release?

**Comment by gplssm** [comment]
Yes! Just merge #63 into dev and release it.
