### ISSUE TITLE
Release 0.4.5

### ISSUE THREAD

**Issue by ulfmueller** [openego/ego.io#66]
The clean run dp 0.4.5 was finished. Therefore and due to the [ego release week](https://github.com/openego/eGo/issues/96) and the corresponding dependencies we want to release ego.io.

So far, I have only released it the 'quick and not so clean' way by releasing it based on the dev. I suppose it is cleaner and appropriate to do it with sql codegen this time. 

Is anyone interested in releasing?
Otherwise I will go through [the steps](https://github.com/openego/ego.io/wiki/How-to-update-database-definitions) and do so...

**Comment by ulfmueller** [comment]
@nesnoj I want to run codegen now. Concerning the process described in the wiki, what kind of credentials you want me to stash when running codegen?

**Comment by ulfmueller** [comment]
ah you probably mean after running codegen. So not pushing the credentials which I have to enter in codegen...

**Comment by ulfmueller** [comment]
@birgits @maltesc @wolfbunke @ClaraBuettner @BartelsJ 
I created a new release branch and did the sqlacodegen. Could you please checkout to the [0.4.5 branch](https://github.com/openego/ego.io/tree/release_v0.4.5) and test your functionalities in eDisGo, eGo, eTraGo, ding0 (...) within the next like 5 hours? 
If you need to apply changes, apply them to this branch. 
After this testing I will merge it into dev and release it.

**Comment by ulfmueller** [comment]
@MGlauer 
Concerning this new release, I was wondering if one would need anything in the [setup install_requires](https://github.com/openego/ego.io/blob/dev/setup.py#L14) for the new oedialect? If yes, could you add it today?

**Comment by wolfbunke** [comment]
eGo works fine on the new release branch.

**Comment by ulfmueller** [comment]
with the recent changes eTraGo seems to be fine as well!

**Comment by birgits** [comment]
ding0 and edisgo work as well!

**Comment by ulfmueller** [comment]
@birgits you did not have to change anything manually?

**Comment by ulfmueller** [comment]
ego.io is released on github now. I will upload it to pypi tomorrow morning. Until then, if you notice anything I could still reset/revert/change stuff and recreate the release... But pypi does not forget, then it will be the release 0.4.5. forever once I upload it there.

**Comment by birgits** [comment]
> @birgits you did not have to change anything manually?

Nope, it worked after all. I don't know what went wrong in the first place but on the second try everything was fine.

@ulfmueller when will you upload the new release to pypi? I need it for the ding0 release later on.

**Comment by ulfmueller** [comment]
The new version is available at pypi! :tada:
