### ISSUE TITLE
problem with sqlalchemy

### ISSUE THREAD

**Issue by ulfmueller** [openego/ego.io#7]
@gplssm @MGlauer
When performing the data processing I got an error due to the ".base" in the following line
`
from sqlalchemy.dialects.postgresql.base import ARRAY
`
-> line 6 https://github.com/openego/ego.io/blob/master/egoio/db_tables/calc_ego_loads.py

I seems that the code was written with an older version of sqlalchemy. 
The code only works when I change the line towards:
`
from sqlalchemy.dialects.postgresql import ARRAY
`

Does anyone disagree with changing this in order to be compatible with sqlalchemy 1.1.2 ?

**Comment by gplssm** [comment]
The problem was already described over here #6 and I temporally solved it by installing an older SQLAlchemy version like 1.0.15.

I'm fine with you proposed change.

**Comment by ulfmueller** [comment]
sorry that I didnt see /forgot about that issue. Ok I just changed it...

**Comment by gplssm** [comment]
Thanks :+1: 

If solved, pleas close #6, #7
