### ISSUE TITLE
Fix oedialect dependency

### ISSUE THREAD

**Issue by nesnoj** [openego/ego.io#81]
I'll do the release of v0.4.6 today, one ugly issue remains: the oedialect dependency to its master branch.
Can we hotfix our release (also on pypi?) as soon as a new oedialect release is done? If not, we could do another release 0.4.7

**Comment by gplssm** [comment]
> Can we hotfix our release (also on pypi?) as soon as a new oedialect release is done? If not, we could do another release 0.4.7

What do you mean by this? Changing the dependency specification of oedialect after the release 0.4.6? AFAIK we have to do another release, even if it's just a small change...

**Comment by nesnoj** [comment]
> What do you mean by this? Changing the dependency specification of oedialect after the release 0.4.6?

Yes.
It's good to have the current master in there for now but I'd prefer to have just '`oedialect` as dependency (which depends on the upcoming release of it). As long as the master of oedialect is always the current stable (which I strongly suppose) the result is the same, it's just a mater of taste.. but it's also ok to postpone for next regular release.

**Comment by nesnoj** [comment]
Critical problem:
ego.io is **not installable** via PYPI:
```
ERROR: Packages installed from PyPI cannot depend on packages which are not also hosted on PyPI.
egoio depends on oedialect@ https://github.com/OpenEnergyPlatform/oedialect/archive/master.zip 
```
The way we chose for 0.4.6 doesn't work, we depend on a proper oedialect release, at least for installs via PYPI.. 
@MGlauer @Bachibouzouk

**Comment by Bachibouzouk** [comment]
Why not simply write `oedialect` ? You need recent code?

**Comment by gplssm** [comment]
> Why not simply write oedialect ? You need recent code?

Exactly, we need code changes that we're made after the last release on PyPi which are included in the current master of oedialect. Once, oedialect is released again, we can simply use "oedialect"

**Comment by Bachibouzouk** [comment]
I'm preparing a release candidate (I'll link the PR here once created)

**Comment by nesnoj** [comment]
> I'm preparing a release candidate (I'll link the PR here once created)

Great, I'm raring to go... :+1:

**Comment by Bachibouzouk** [comment]
@nesnoj, @gplssm  : @MGlauer made a release [v0.0.6](https://github.com/OpenEnergyPlatform/oedialect/releases/tag/0.0.6) and also pushed it on [PyPi](https://pypi.org/project/oedialect/). So it should solve your problem !

**Comment by nesnoj** [comment]
> @nesnoj, @gplssm : @MGlauer made a release [v0.0.6](https://github.com/OpenEnergyPlatform/oedialect/releases/tag/0.0.6) and also pushed it on [PyPi](https://pypi.org/project/oedialect/). So it should solve your problem !

Thx, I'll check

**Comment by nesnoj** [comment]
Yepp, [v0.4.7](https://github.com/openego/ego.io/releases/tag/v0.4.7) finally works :). Thx @Bachibouzouk @MGlauer 

(wow it did took quite some time to show up on pypi..)
